---
abstract: 'Manipulate CSV files from the command line'
author:
  - 'Gaal\ Yahas\ \<gaal\@forum2\.org\>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CSV
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-CSV
  repository: https://github.com/gaal/app-csv.git
version: 0.07
