--- #YAML:1.0
name:               App-CSV
version:            0.04
abstract:           Manipulate CSV files from the command line
author:
    - Gaal\ Yahas\ \<gaal\@forum2\.org\>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::String:      0
    Moose:           0
    MooseX::Getopt:  0
    Text::CSV_XS:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
