--- #YAML:1.0
name:                App-CSV
version:             0.05
abstract:            Manipulate CSV files from the command line
license:             mit
author:              
    - Gaal\ Yahas\ \<gaal\@forum2\.org\>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::String:                    0
    Moose:                         0
    MooseX::Getopt:                0
    Text::CSV_XS:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
