# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-CSV
version:      0.01
version_from: 
installdirs:  site
requires:
    IO::String:                    0
    Moose:                         0
    MooseX::Getopt:                0
    Text::CSV_XS:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
